application:
  name: link-rating
  project: link-rating
  cloud_region: aws/us-east-1
  publicly_accessible: true
routers:
- name: main
  custom_domains:
  - branch: master
    domain: linkrating.spinscale.de
  routes:
  - application_name: link-rating
    paths:
    - /*
